### ISSUE TITLE
ERROR in MatTooltipModule is not an NgModule

### ISSUE THREAD

**Issue by ninaanatchkova** [Centroida/ngx-image-editor#1]
The compiler throws "ERROR in MatTooltipModule is not an NgModule"

**Comment by Kaizeras** [comment]
Solved in #1

**Comment by strypeez** [comment]
I am getting this error when I run ng-serve, but if I hit Ctrl S on any file it compiles. Also running into the error `ERROR in Unexpected value 'MatTooltipModule in /Users/strypeez/Dropbox/gosco-webNEW/gosco-webUPTODATE/node_modules/@angular/material/tooltip/typings/index.d.ts' imported by the module 'AppModule in /Users/strypeez/Dropbox/gosco-webNEW/gosco-webUPTODATE/src/app/app.module.ts'. Please add a @NgModule annotation.`
