### ISSUE TITLE
MdDialogRef doesn't exist, Directives from material.angular.io had changed

### ISSUE THREAD

**Issue by deokey** [Centroida/ngx-image-editor#4]
Hi, im pleased to say that id love to use this image editor on my work but the directives from [Material.angular.io](https://material.angular.io/) have been changed since you used it to perform the latest version of ngx-image-editor, i've seen that Md is now a Mat preffix so the plugin is not working, should update the code to use the latest version of material.angular.io to make it running again?

I've tried to do some manual replacement from MdDialogRef to MatDialog but doesn't work, i have no clue to do it by my own, im a newbie into ng2+ and using the material.angular.io library but i really want to use it, that do you think about this fix? 

thanks a lot for your time, hope you answer.

![captura de pantalla 2017-11-21 a la s 5 02 13 p m](https://user-images.githubusercontent.com/18384611/33097383-68a6626e-cee0-11e7-82b6-4e24de19511f.png)

ERROR in node_modules/ngx-image-editor/lib/ngx-image-editor.component.d.ts(2,10): error TS2305: Module '"/.../node_modules/@angular/material/material"' has no exported member 'MdDialogRef'.

**Comment by Taulantdisha** [comment]
The issue should be fixed now. The editor will be used as a component now not as Material Dialog component.
