### ISSUE TITLE
Live Demo is not working.

### ISSUE THREAD

**Issue by harshals13** [Centroida/ngx-image-editor#9]
The live demo would help us so much in implementing the editor.

**Comment by tatsujb** [comment]
up.

please do something.

**Comment by harshals13** [comment]
Unless the angular rxjs issue is fixed there's nothing that can be done. So, I believe you have to wait until the authors find a fix.

**Comment by Taulantdisha** [comment]
Live demo is now available at https://centroida.github.io/ngx-image-editor/

**Comment by tom94zoe** [comment]
If I open the link above an 404-not found error is displayed
